"""SONIC sim2sim with Inspire RH56DFQ hands driven by the rh56 stream (stage 2).

Same sim as gear_sonic/scripts/run_sim_loop.py (the wbc yaml now points at
scene_53dof_rh56.xml — generated by hand_viewer/make_rh56_model.py), plus a
wrapped sim_step that kinematically writes the 24 finger joints from the
latest `left/right_hand_rh56` values on the :5556 pose stream. The finger
motors exist only to preserve BaseSimulator's actuator_id==joint_id-1 torque
scatter; their ctrl stays zero (NUM_HAND_MOTORS=0), so qpos writes don't fight
any PD controller. Follows the sonic_bench sim_server.py instance-patch
pattern — zero gear_sonic code changes.

Run on the host:
  .venv_sim/bin/python tools/webcam2motion/run_sim_rh56.py [--demo]
"""

import argparse
import os
import sys
import time

import mujoco
import numpy as np

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, REPO)
sys.path.insert(0, os.path.join(REPO, "tools/webcam2motion/hand_viewer"))

from gear_sonic.utils.mujoco_sim.configs import SimLoopConfig  # noqa: E402
from gear_sonic.utils.mujoco_sim.simulator_factory import (  # noqa: E402
    SimulatorFactory,
    init_channel,
)

from hand_viewer import RH56_ORDER, Rh56Subscriber, _axes  # noqa: E402


class FingerDriver:
    """rh56 (6,) 0..1 -> qpos for the 12 prefixed finger joints of one hand."""

    def __init__(self, model: mujoco.MjModel, side: str):
        self.side = side
        S = "L" if side == "left" else "R"
        self._axes_map = []
        for axis, (driven, followers) in _axes(S).items():
            entries = []
            for name, mult in [(driven, 1.0)] + followers:
                jid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT,
                                        f"{side}_hand_{name}")
                if jid >= 0:
                    entries.append((model.jnt_qposadr[jid], model.jnt_dofadr[jid],
                                    *model.jnt_range[jid], mult))
            self._axes_map.append((RH56_ORDER.index(axis), entries))

    def write(self, data: mujoco.MjData, cmd: np.ndarray):
        for idx, entries in self._axes_map:
            v = float(np.clip(cmd[idx], 0, 1))
            if not entries:
                continue
            _, _, lo0, hi0, _ = entries[0]
            q0 = lo0 + v * (hi0 - lo0)
            for qadr, dofadr, lo, hi, mult in entries:
                data.qpos[qadr] = np.clip(q0 * mult, lo, hi)
                data.qvel[dofadr] = 0.0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=5556, help="pose stream port")
    ap.add_argument("--demo", action="store_true", help="sinusoid, no stream needed")
    args = ap.parse_args()

    config = SimLoopConfig(interface="sim")
    wbc_config = config.load_wbc_yaml()
    wbc_config["ENV_NAME"] = config.env_name
    init_channel(config=wbc_config)
    sim = SimulatorFactory.create_simulator(
        config=wbc_config, env_name=config.env_name,
        onscreen=wbc_config.get("ENABLE_ONSCREEN", True),
        offscreen=False, enable_image_publish=False,
    )
    env = sim.sim_env
    drivers = [FingerDriver(env.mj_model, "left"), FingerDriver(env.mj_model, "right")]

    sub = None
    if not args.demo:
        sub = Rh56Subscriber("localhost", args.port)
        sub.start()
        print(f"[rh56-sim] fingers driven by rh56 fields on :{args.port}")

    t0 = time.time()
    orig_sim_step = env.sim_step

    def sim_step_with_fingers():
        if args.demo:
            wave = 0.5 * (1 + np.sin(2 * np.pi * 0.2 * (time.time() - t0)))
            cmd = {s: np.full(6, wave) for s in ("left", "right")}
        else:
            cmd = {s: sub.latest[s] for s in ("left", "right")}
        for d in drivers:
            if cmd[d.side] is not None:
                d.write(env.mj_data, np.asarray(cmd[d.side]))
        orig_sim_step()

    env.sim_step = sim_step_with_fingers
    sim.start()


if __name__ == "__main__":
    main()
